import { SourceCitation } from './SourceCitation';

interface MessageBubbleProps {
  role: 'user' | 'assistant';
  content: string;
  sources?: Array<{ file: string; preview: string }>;
  provider?: string;
}

export function MessageBubble({ role, content, sources, provider }: MessageBubbleProps) {
  const isUser = role === 'user';

  // Minimal Markdown renderer
  const renderMarkdown = (text: string) => {
    if (!text) return { __html: '' };

    let html = text
      // Escape HTML
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      // Code blocks (```code```)
      .replace(/```([\s\S]*?)```/g, '<pre class="bg-zinc-950 p-3 rounded-md my-2 overflow-x-auto text-xs font-mono border border-zinc-800 text-zinc-300"><code>$1</code></pre>')
      // Inline code (`code`)
      .replace(/`([^`]+)`/g, '<code class="bg-zinc-950 px-1.5 py-0.5 rounded text-[0.9em] font-mono border border-zinc-800 text-indigo-300">$1</code>')
      // Bold (**text**)
      .replace(/\*\*([^*]+)\*\*/g, '<strong class="font-semibold text-zinc-100">$1</strong>')
      // Headings
      .replace(/^### (.*$)/gim, '<h3 class="text-base font-semibold mt-4 mb-2 text-white">$1</h3>')
      .replace(/^## (.*$)/gim, '<h2 class="text-lg font-bold mt-5 mb-2 text-white border-b border-zinc-800 pb-1">$1</h2>')
      .replace(/^# (.*$)/gim, '<h1 class="text-xl font-extrabold mt-6 mb-3 text-white">$1</h1>')
      // Paragraphs
      .replace(/\n\n/g, '</p><p class="my-2 leading-relaxed">')
      // Single line breaks
      .replace(/\n/g, '<br />');

    // Wrap in initial p tag
    html = `<p class="leading-relaxed mb-0 text-zinc-300">${html}</p>`;

    // Clean up empty tags that might have been created
    html = html.replace(/<p[^>]*><\/p>/g, '');

    return { __html: html };
  };

  return (
    <div className={`flex flex-col w-full mb-8 ${isUser ? 'items-end' : 'items-start'}`}>
      <div className={`flex w-full ${isUser ? 'justify-end' : 'justify-start'}`}>
        {!isUser && (
          <div className="w-8 h-8 rounded-full bg-gradient-to-br from-indigo-500 to-indigo-600 flex items-center justify-center shrink-0 mr-4 mt-1.5 shadow-md shadow-indigo-500/20 border border-indigo-400/20">
            <div className="w-2.5 h-2.5 bg-white/90 rounded-full shadow-inner"></div>
          </div>
        )}
        <div 
          className={`max-w-[85%] ${
            isUser 
              ? 'bg-zinc-800/80 backdrop-blur-md border border-zinc-700/50 text-zinc-100 rounded-3xl rounded-tr-md px-6 py-3.5 shadow-sm' 
              : 'text-zinc-200 mt-1.5 relative group'
          }`}
        >
          {isUser ? (
            <div className="whitespace-pre-wrap leading-relaxed text-[15px]">{content}</div>
          ) : (
            <>
              <div 
                className="markdown-body text-[15px] leading-relaxed prose prose-invert max-w-none"
                dangerouslySetInnerHTML={renderMarkdown(content)} 
              />
              {provider && (
                <div className="absolute -top-7 right-0 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                  <span className="text-[10px] px-2.5 py-1 rounded-full bg-zinc-800/80 backdrop-blur-sm text-zinc-400 border border-zinc-700/50 shadow-sm">
                    Generated by {provider === 'cohere' ? 'Cohere Command R' : 'Google Gemini Flash'}
                  </span>
                </div>
              )}
            </>
          )}
        </div>
      </div>
      
      {!isUser && sources && sources.length > 0 && (
        <div className="max-w-[85%] w-full ml-12 mt-4">
          <SourceCitation sources={sources} />
        </div>
      )}
    </div>
  );
}
